#!/bin/sh
# Guardrail: block commits that add clippy lints. Install once per clone:
#   ln -sf ../../scripts/pre-commit .git/hooks/pre-commit
# Bypass for a WIP commit: git commit --no-verify
set -e
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
cargo clippy --all-targets --quiet -- -D warnings
